project/urls.py
from django.contrib import admin
from django.urls import path
import app.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', app.views.index, name='index'),
    path('app/index/', app.views.index, name='index'),
    path('app/create/', app.views.create, name='create'),
    path('app/new/', app.views.blogform, name='new'),
    path('app/<int:pk>/edit/', app.views.edit, name='edit'),
    path('app/<int:pk>/remove/', app.views.remove, name='remove'),
    path('app/<int:blog_id>', app.views.detail, name='detail'),
    path('app/hashtag/', app.views.hashtagform, name='hashtag'),
    path('app/<int:hashtag_id>/search/', app.views.search, name='search'),
]

app/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    body = models.TextField()
    hashtags = models.ManyToManyField('Hashtag', blank=True)

    def __str__(self):
        return self.title
    
    def summary(self):
        return self.body[:100]

class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

app/forms.py
from django import forms
from .models import Blog, Hashtag

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'body', 'hashtags']

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .forms import BlogForm, HashtagForm
from .models import Blog, Hashtag

# Create your views here.
def layout(request):
    return render(request, 'app/layout.html')

def index(request):
    blogs = Blog.objects
    hashtags = Hashtag.objects
    return render(request, 'app/index.html', {'blogs': blogs, 'hashtags': hashtags})

def search(request, hashtag_id):
    hashtag = get_object_or_404(Hashtag, pk=hashtag_id)
    return render(request, 'app/search.html', {'hashtag': hashtag})

def new(request):
    return render(request, 'app/new.html')

def create(request):
    blog = Blog()
    blog.title = request.GET['title']
    blog.body = request.GET['body']
    blog.pub_date = timezone.datetime.now()
    blog.save()
    return redirect('/app/index/')

def blogform(request, blog=None):
    if request.method == 'POST':
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.pub_date = timezone.datetime.now()
            blog.save()
            form.save_m2m()
            return redirect('index')
    else:
        form = BlogForm(instance=blog)
        return render(request, 'app/new.html', {'form': form})

def hashtagform(request, hashtag=None):
    if request.method == 'POST':
        form = HashtagForm(request.POST, instance=hashtag)
        if form.is_valid():
            hashtag = form.save(commit=False)
            if Hashtag.objects.filter(name=form.cleaned_data['name']):
                form = HashtagForm()
                error_message = "이미 존재하는 해시태그 입니다."
                return render(request, 'app/hashtag.html', {'form': form, "error_message": error_message})
            else:
                hashtag.name = form.cleaned_data['name']
                hashtag.save()
                return redirect('index')
    else:
        form = HashtagForm(instance=hashtag)
        return render(request, 'app/hashtag.html', {'form': form})

def edit(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    return blogform(request, blog)

def remove(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    blog.delete()
    return redirect('index')

def detail(request, blog_id):
        blog_detail = get_object_or_404(Blog, pk=blog_id)
        return render(request, 'app/detail.html', {'blog': blog_detail})

app/templates/app/detail.html
{% extends 'app/layout.html' %}

{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('/static/app/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Detail Blog</h1>
            <span class="subheading">디테일 페이지 입니다.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
<div class="container">
    <div class="col-lg-8 col-md-10 mx-auto">
        <h1>{{ blog.title }}</h1>
        <p>{{ blog.pub_date }}</p>
        <p>{{ blog.body }}</p>
        {% for hashtag in blog.hashtags.all %}
          <span>{{ hashtag.name }}</span>
        {% endfor %}
        <br>
        <a class="btn btn-outline-secondary btn-sm" href="{% url 'edit' pk=blog.pk %}">수정</a>
        <a class="btn btn-outline-secondary btn-sm" href="{% url 'remove' pk=blog.pk %}">삭제</a>
        <a class="btn btn-outline-secondary btn-sm" href="{% url 'index' %}">홈으로</a>
    </div>
</div>
{% endblock %}

app/templates/app/hashtag.html
{% extends 'app/layout.html' %}

{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('/static/app/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>New Hashtag</h1>
            <span class="subheading">해시태그를 추가하는 페이지 입니다.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
<div class="container">
    <div class="col-lg-8 col-md-10 mx-auto">
        {{ error_message }}
        <form method="POST">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input class="btn btn-dark" type="submit" value="제출하기">
        </form>
    </div>
</div>
{% endblock %}

app/templates/app/index.html
{% extends 'app/layout.html' %}

{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('/static/app/img/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Clean Blog</h1>
          <span class="subheading">A Blog Theme by Start Bootstrap</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block content %}
<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      {% for blog in blogs.all %}
      <div class="post-preview">
        <a href="{% url 'detail' blog.id %}">
          <h2 class="post-title">
            {{ blog.title }}
          </h2>
          <h3 class="post-subtitle">
            {{ blog.summary }}
          </h3>
        </a>
        <p class="post-meta">
          {{ blog.pub_date }}</p>
      </div>
      <hr>
      {% endfor %}
      <!-- Pager -->
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/app/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'app/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'app/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'app/css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">Blog</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'new' %}">New</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'hashtag' %}">Add hashtag</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block header %}
  {% endblock %}

  {% block content %}
  {% endblock %}

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'app/js/clean-blog.min.js' %}"></script>

</body>

</html>

app/templates/app/new.html
{% extends 'app/layout.html' %}

{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('/static/app/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>New Blog</h1>
            <span class="subheading">글쓰기 페이지 입니다.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
<div class="container">
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="POST">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input class="btn btn-dark" type="submit" value="제출하기">
        </form>
    </div>
</div>
{% endblock %}

app/templates/app/search.html
{% extends 'app/layout.html' %}

{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('/static/app/img/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>{{ hashtag }}가 있는 게시글 목록</h1>
          <span class="subheading">해시태그 검색결과 페이지 입니다.</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block content %}
<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      {% for blog in hashtag.blog_set.all %}
      <div class="post-preview">
        <a href="{% url 'detail' blog.id %}">
          <h2 class="post-title">
            {{ blog.title }}
          </h2>
          <h3 class="post-subtitle">
            {{ blog.summary }}
          </h3>
        </a>
        <p class="post-meta">
          {{ blog.pub_date }}</p>
      </div>
      <hr>
      {% endfor %}
      <!-- Pager -->
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}